### ISSUE TITLE
feature request: support tunable white

### ISSUE THREAD

**Issue by CFenner** [lkempf/casambi-bt-hass#11]
My luminaries come a tunable white and I would like to control this via HA:

```
Unit(
  _typeId=22133, deviceId=1, uuid='x', address='x', name='CURVED ', 
  firmwareVersion='9472', 
  unitType=UnitType(
    id=22133, model='CURVED ', manufacturer='OLIGO', 
    mode='PWM/4ch/Dim,Dim,TW', stateLength=3, 
    controls=[
      UnitControl(type=<UnitControlType.DIMMER: 0>, offset=0, length=8, default=128, readonly=False), 
      UnitControl(type=<UnitControlType.DIMMER: 0>, offset=8, length=8, default=128, readonly=False), 
      UnitControl(type=<UnitControlType.UNKOWN: 99>, offset=16, length=8, default=46, readonly=False)]
    ),
    _state=None, _on=False, _online=True
  )
```

The third control is stated here as `UNKNOWN` which is the TW control. It's also mentioned in the `mode`: `PWM/4ch/Dim,Dim,TW`

**Comment by lkempf** [comment]
I've tried to implement this but can't test it due to lack of suitable hardware. I also can't really test anything anymore because I'm no longer at my parents house. Can you check if this works for you? The current implementation is limited to units (so no groups) because I don't understand the SetTemperature opcode.

**Comment by lkempf** [comment]
I just noticed that it probably won't work. You first need to delete the caches created by casambi-bt. You can just delete the folder `Casambi-Bt-Store` or something like in your HA config folder.

I should probably also change the caching system so that this step won't be necessary any more...

**Comment by lkempf** [comment]
This should be implemented by now.

**Comment by macflei** [comment]
Hat das mal jemand getestet? Bei mir springt die Farbtemperatur nach dem Einschalten via HA (egal ob über Ein oder über Dimmwert) immer auf den Max-Wert. Änderung der Farbtemperatur geht dann auch nur über die App.
