### ISSUE TITLE
Show network in "connected via" field of units

### ISSUE THREAD

**Issue by CFenner** [lkempf/casambi-bt-hass#12]
Like here in the ZHA integration Casambi integration could fill the [via_device](https://developers.home-assistant.io/docs/device_registry_index/#device-properties) field to show that luminaires are connected via the network device.

<img width="338" alt="Bildschirm­foto 2022-12-29 um 09 53 19" src="https://user-images.githubusercontent.com/9592452/209930784-9ca2187e-9b9f-42fe-b2cf-cbf1ad5e7506.png">

**Comment by lkempf** [comment]
I'm already setting `via_device` but it doesn't seem to have the intended effect. I'll look into that.

**Comment by CFenner** [comment]
fixed
