### ISSUE TITLE
Keeps discovering single light

### ISSUE THREAD

**Issue by tjorim** [lkempf/casambi-bt-hass#27]
![Screenshot_20230322-162746.png](https://user-images.githubusercontent.com/1294876/226959712-d02d20d5-29de-4fee-be5a-9175605c8711.png)

![Screenshot_20230322-162740.png](https://user-images.githubusercontent.com/1294876/226959711-71ba6c67-2ff7-480a-9335-69aadbdd08a8.png)

**Comment by lkempf** [comment]
I would need some logs to investigate this. I'm pretty sure that there is a way to turn on logging for just HA discovery but I'd have to look into that. I'll try to do that sometimes around Easter unless you figure it out on your own until then.

**Comment by lkempf** [comment]
I have looked into this a bit. The new version adds some logging regarding discoveries. However, I suspect that the issue is an old config entry. Could you try to remove the integration and add it again?

**Comment by lkempf** [comment]
Thanks for the logs. The discoveries happen on multiple MACs with the characteristic I'm looking for. I guess only  I've added even more logs to discovery events and this should help to confirm a theory I have on how to fix this. Could you update to the latest commit and send me all lines in the log which contain "Discovery"?

**Comment by lkempf** [comment]
Are you still affected by this? If yes does the new discovery filter in v0.1.0 help?

**Comment by tjorim** [comment]
It was quite infrequent but can't say it happened recently. The new version is really stable and haven't had a single disconnect. 🤞
