### ISSUE TITLE
Broken after update HA version 2023.4.1

### ISSUE THREAD

**Issue by Artemiy117** [lkempf/casambi-bt-hass#29]
Everything worked before the update HA on version 2023.4.1
After it integration is broken.

**Comment by lkempf** [comment]
Please provide logs and what version of the integration you are using. The latest pre-release might fix your issue but I haven't been able to release that yet because it causes log spamming for at least one user.

**Comment by lkempf** [comment]
There is also version 0.0.6 now which works for me on HA 2023.04.1. Does this fix your issue?

**Comment by Artemiy117** [comment]
Yes, all working on 0.0.7 fine.
