### ISSUE TITLE
Bluetooth gateway (using Shelly) - would it be possible?

### ISSUE THREAD

**Issue by triumfas** [lkempf/casambi-bt-hass#39]
**Is your feature request related to a problem? Please describe.**
Possibility to control lights using Shelly Bluetooth gateway.

**Describe the solution you'd like**
Allow sending control commands through Shelly BT gateway and HA integration.

**Additional context**
Devices seems to be discovered, but integration requires bluetooth device connected to HA, which I don't have and most likely it would be a pain to have as I use docker container on NAS. So could it at least in theory work?

**Comment by lkempf** [comment]
I only require that the bluetooth controller supports connecting to the device. I guess the problem in this case is that the shelly bluetooth gateway in HA supports discovery but not connecting to a specific device. This makes it incompatible with this integration.
