### ISSUE TITLE
feature request: supports simple string as address in setup

### ISSUE THREAD

**Issue by CFenner** [lkempf/casambi-bt-hass#4]
When you do not use the BLE adress provided by auto discovery you need to type in the address `:` separated and all upper case. Device lookup otherwise fails.

It would be nice to also support a simple string and adjust it to BLE address format under the hood (e.g. `12abcd345678`).

Maybe something for a later state.

**Comment by mintnl** [comment]
The address thing on setup got me a bit confused. However the auto detected string is correct and works. 
This string is referred to as the NetworkID in the Casambi app. Maybe a clearification while setting up is handy.

**Comment by lkempf** [comment]
Where in the app did you find this? I can't seem to find it on Android. At least internally Casambi has a NetworkId that isn't the correct address. The correct value is called the network uuid internally.

**Comment by CFenner** [comment]
In my case the „network id“ shown in the app is also the ble address. 

> Where in the app did you find this?

Double Klick on an light and go to details.

**Comment by mintnl** [comment]
This is on iOS

![IMG_2511](https://user-images.githubusercontent.com/1941539/212032774-57c24692-0453-4d69-8ea1-e6fc0e4d95f9.PNG)
![IMG_2512](https://user-images.githubusercontent.com/1941539/212032799-b1303a61-b229-4c35-ab10-802660a72c92.PNG)
