### ISSUE TITLE
Casambi relay not getting detected

### ISSUE THREAD

**Issue by LenPoppe** [lkempf/casambi-bt-hass#40]
Hi,

I integrated the casambi-bt-hass in my HA and everything works fine, only one casambi-relay that is not getting noticed:

 

![Screenshot_20231015_135859_Casambi](https://github.com/lkempf/casambi-bt-hass/assets/44391866/bafefeee-4fa3-4998-8d73-309e1e8bde33)

Do you have an idea why it doesn't find this relay?

All my senes I created are detected and i can activate a scene where this relay is triggered and working...

**Comment by lkempf** [comment]
Are you using the latest version of the integration? The unit you are using only has support for onoff and that was implemented as part of one of the newer releases.

If the unit shows up but can't be controlled properly you might want to update to the latest commit in HCAS (the version called main).

**Comment by LenPoppe** [comment]
I updated the python scripts manualy and now the relay is detected. But the strange thing now is that it's default set to ON and when I set it to OFF it goess back to ON.

**Comment by lkempf** [comment]
Ok then it seems like I haven't found the bug yet. Closing because this is the same issue as in #33 .
