### ISSUE TITLE
Issues with initial setup

### ISSUE THREAD

**Issue by ldehaas1612** [lkempf/casambi-bt-hass#64]
**Description of the bug**
When homeassistant starts, casambi is being discovered, then I enter (what I think) is the correct password and I immediately get an unexpected error in return.
Thanks for any help in advance!

**To Reproduce**
1. Boot homeassistant and go to devices.
2. Click on casambi_bt
3. Enter the password and check the MAC address is correct.
4. be greeted with the error explained.

**Screenshots**
picture of the error
![Unexpected error](https://github.com/lkempf/casambi-bt-hass/assets/7444561/737d497f-6a38-4825-aaf6-41ec0e225b65)

**Versions**
- HA version: v0.1.0
- Integration version: 

**Logs**
[home-assistant_2023-12-27T17-41-16.959Z.log](https://github.com/lkempf/casambi-bt-hass/files/13780310/home-assistant_2023-12-27T17-41-16.959Z.log)

**Comment by ldehaas1612** [comment]
Still might be worth investigating this further, but I found a valid workaround to be creating a new network in Casambi and moving all compatible devices into the new network one by one. Only then I would start the integration and afterwards finish adding new devices to casambi app such as the smart button and hue integration (since HA is not fully setup yet).
Thanks for the awesome integration! Now it works just perfect and I love the fact that it's a non cloud integration. Keep up the good work!

**Comment by lkempf** [comment]
Thanks. I've already looked at the log you attached and there seems to be an error handling invalid unit types. However, I can't tell why your network has a unit with invalid type.

**Comment by ldehaas1612** [comment]
Right, yeah that was my thought after two days of trying as well. We have a Xpress remote from casambi, Philips Hue linked and some Occhio fixtures. I feel like in hindsight it must be the remote that was the culprit. Or would Hue connectivity also mess with the functionality? Thanks for the quick support!

**Comment by bikeophilipp** [comment]
Having the same issue and error message as @ldehaas1612 . I have only one Occhio Mito Sospeso in one Network and I get the error. Password and connection from other devices work.
Maybe the Device is not supported?

**Comment by ldehaas1612** [comment]
@bikeophilipp, I actually managed to get everything working in the end! We also have de Occhio Mito Sospeso and another Occhio light fixture, but they work just fine. What I did in the end was creating a new network, placing all devices I knew worked on this platform in there. So all light fixtures, no Philips Hue bridge and no remotes/switches. Then attaching the system to Casambi as instructed by the project and then if you want/need, add the remote and Hue bridge back into the Casambi or Occhio Air app afterwards. Doing this allowed me to have control in every way possible
Hope this helps you out also.

**Comment by reda1978** [comment]
@bikeophilipp Could you by any change with this setup control the vertical lighting of Mito Sospeso? I mean only through BT not with Casambi API. Me, I can’t. Nor the temperature control.

**Comment by ldehaas1612** [comment]
@reda1978, you were referencing @bikeophilipp, but since he doesn't have a working setup, I thought I'd chip in my experience. For me, I can actually control brightness and temperature using home assistant. However the up/down mode I haven't figured out yet. I think it might me supported by @lkempf, but so far there are no cards that properly support it I think. Right now I'm using the minimalist ui theme to set the lights.

**Comment by reda1978** [comment]
Sorry for the referencing :-)

From my end, I gave up the BT setup and went with the Casamabi API to have full control over lighting features with HA. But I am still hoping that the BT setup will allow for vertical lighting and having everything in local network.

Cheers,

**Comment by bikeophilipp** [comment]
Hi @ldehaas1612 thanks for the support. I will create a new network first and add the one lamp that I have. Hope it works.
Could you also help me with finding the BT MAC address? I cannot find it anywhere in the App. Maybe you could provide a screenshot? 
When I connect with the addonn however it shows me a MAC address which I assume is the correct one...?
@reda1978 The up/down control is not so important for me and also explained in the Readme that this does not work. 
Just changing the brightness and turning it on/off is sufficient for now

**Comment by ldehaas1612** [comment]
@reda1978, I went and upgraded to the evolution version for the network and am therefore not able to use the api anymore. Also, no new api developer codes were supplied by Casambi Europe, so that was no option for me anyways. I'll keep using the BT way right now since it does everything I want anyways 😅

**Comment by ldehaas1612** [comment]
@bikeophilipp no worries, i think there was a detailed description out there somewhere, but I made some screenshots anyways. 
![Screenshot_20240216-114626~3](https://github.com/lkempf/casambi-bt-hass/assets/7444561/2edf1de6-dac0-4b19-bcd8-60ec38ae8c66)
![Screenshot_20240216-114637~2](https://github.com/lkempf/casambi-bt-hass/assets/7444561/0de3a586-f90d-4b3f-814b-8dda433a9ff4)
![Screenshot_20240216-114725~3](https://github.com/lkempf/casambi-bt-hass/assets/7444561/4cf5d9d7-17f5-4c7d-a768-be361539da0c)
Short written version is:
Go to your casambi/occhio air app.
Go to your network you want to incorporate
Top right corner, select edit and click on any light in the network
Go to details
NetworkID: This is you network MAC address.
Make sure your new network follows all details and features as suggested by Ikempf in the readme.
Hope this helps!

**Comment by bikeophilipp** [comment]
@ldehaas1612 you helped a lot. I did exactly as you said in creating a new network and added my lamp. I had to update the Firmware from Classic to Evolution first but after the new network was created and the lamp added, the HA Addon worked smooth.
@lkempf Thanks a lot for the addon. Really helps a lot to manage my lamp using HA

**Comment by lkempf** [comment]
I just fixed the underlying bug in CasambiBt, it should work without separating networks in the next integration version.
