### ISSUE TITLE
Invalid supported color modes

### ISSUE THREAD

**Issue by tjorim** [lkempf/casambi-bt-hass#70]
**Describe the bug**
Deprecation warning on HA beta 2024.3.
I think this is related to https://developers.home-assistant.io/blog/2024/02/12/light-color-mode-mandatory/

**To Reproduce**
1. Update HA core to version 2024.3
2. Check the error logs

**Versions**
- HA version: 2024.3.0b3
- Integration version: v0.1.0

**Logs**
```
Logger: homeassistant.components.light
Source: components/light/__init__.py:1165
integration: Light (documentation, issues)
First occurred: 02:19:12 (1 occurrences)
Last logged: 02:19:12

None (<class 'custom_components.casambi_bt.light.CasambiLightUnit'>) sets invalid supported color modes {'rgbw', 'brightness', 'onoff'}, this will stop working in Home Assistant Core 2025.3, please report it to the author of the 'casambi_bt' custom integration
```

**Comment by lkempf** [comment]
Fixed as of v0.1.3. Thanks for the report.
