### ISSUE TITLE
Failed to load Setup Wizard: 500: Internal Server Error - how to fix it?

### ISSUE THREAD

**Issue by Alexei-vk2** [lkempf/casambi-bt-hass#74]
When you try to install the built-in program "Carambis Bluetooth", it does not appear and displays the message "Setup wizard failed to load: 500: Internal server error" - how can I fix it?

![Снимок экрана 2024-04-07 002028](https://github.com/lkempf/casambi-bt-hass/assets/166062625/41af7968-16e2-4740-ab67-5db6c9ff83f0)
[](url)

![Снимок экрана 2024-04-07 002016](https://github.com/lkempf/casambi-bt-hass/assets/166062625/5fecb80b-7353-4c88-b2f7-1e3d4c00121d)

**Comment by lkempf** [comment]
I'm pretty sure that's an issue with you HA installation. Can you check the logs? My integration does basically nothing until you've selected a network and provided a password and your description doesn't mention you having done this

**Comment by Alexei-vk2** [comment]
The instructions under the last paragraph indicate "Search for the Carambis Bluetooth integration and install it".  At this stage, nothing is specified about entering a username and password.  I am trying to install the "Casambi Bluetooth" integration, but it gives a 500 server error. How can I fix this?



Manual
Place the casambi_bt folder in the custom_components folder.

HACKS
Add this repository as custom repository in the HACK store (HACK -> integration -> custom repositories):

Setup HACKS https://hacs.xyz/
Go to integrations section.
Click on the 3 dots in the top right corner.
Select "Custom repositories"
Add the URL to the repository.
Select the integration category.
Click the "ADD" button.
Search for the Casambi Bluetooth integration and install it.to

**Comment by Alexei-vk2** [comment]
I managed to do everything

**Comment by lkempf** [comment]
I'm not saying that it's an issue with how you installed the integration. I'm saying that it's probably an issue outside of the influence of the integration since the error seems to come from HA itself.

Please check the logs under Settings > System > Logs. The error there should tell you more.

**Comment by hillinator** [comment]
@Alexei-vk2 how have you fixed ist? what was the issue?

**Comment by Alexei-vk2** [comment]
Hello!
Faced with this situation:
Casambi integration is installed in the home assistant.
when the "unavailable" condition occurs, the lights turn on and off.

is there any way to make sure that even after the "not available" state, the devices have the last mode so that they are turned off?
can you tell me how to do this?
![WhatsApp Image 2024-05-13 at 10 57 27](https://github.com/lkempf/casambi-bt-hass/assets/166062625/fd5e03de-d53d-4a3b-8888-896defacf59b)

**Comment by Alexei-vk2** [comment]
> @Alexei-vk2 how have you fixed ist? what was the issue?

нужно, чтобы были включены любые устройства casambi, чтобы обнаружить сеть.

нужно зайти в настройки - устройства и службы - добавить интеграцию.


any casambi devices must be turned on to detect the network.

you need to go to settings - devices and services - add integration



![Снимок экрана 2024-05-30 230714](https://github.com/lkempf/casambi-bt-hass/assets/166062625/4b4b2ec8-2764-4eae-8ee8-725173dcdcbe)
![Снимок экрана 2024-05-30 230603](https://github.com/lkempf/casambi-bt-hass/assets/166062625/8bd0a374-71f4-427b-9b4f-564a35f3f586)
