### ISSUE TITLE
how to update "manual" installation ?

### ISSUE THREAD

**Issue by stbuerger** [lkempf/casambi-bt-hass#92]
Unfortunately I was not able do add a custum repo for this integration in HACS.
Luckily the README mentions the - perfectly working - manual installation by populating `custom_components/casambi_bt`.
Only managing integrations with HACS until now - I'm now wondering how to update this integration to a newer release.
What are the complete and detailed steps for a save and clean update while keeping my configuration intact.
Or do I have to do an integration  delete / re-install cycle ?

**Comment by lkempf** [comment]
If you have a somewhat recent version of the extension (I think from this year) then no data is stored in the `casambi_bt` folder and it can just be replaced. If not then some cached information will be lost but that should be recreated automatically. So just replace the folder.
